version: "3"

services:
  web:
    build: .
    image: smart-translator
    container_name: smart-translator
    restart: always
    # ports:
    #   - 4000:4000
    volumes:
      - "./vol/logs:/app/dist/log"
    environment:
      - VIRTUAL_HOST=sampleapi.example.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=sampleapi.example.com
      - LETSENCRYPT_EMAIL=email@example.com
