version: "3"

services:
  web:
    build: .
    image: smart-translator
    container_name: smart-translator
    restart: always
    ports:
      - 4000:4000
    volumes:
      - "./vol/logs:/app/dist/log"
